// <auto-generated />
using System;
using MayStats_Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MayStats_Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240913191625_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyStats_Rest.Models.Stats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<float>("Bones")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("FatPercentage")
                        .HasColumnType("float");

                    b.Property<float>("FatWeight")
                        .HasColumnType("float");

                    b.Property<float>("IMC")
                        .HasColumnType("float");

                    b.Property<float>("LBM")
                        .HasColumnType("float");

                    b.Property<float>("MetabolicAge")
                        .HasColumnType("float");

                    b.Property<float>("Metabolism")
                        .HasColumnType("float");

                    b.Property<float>("MuscleMassRecordPercentage")
                        .HasColumnType("float");

                    b.Property<float>("ObesityPercentage")
                        .HasColumnType("float");

                    b.Property<float>("ProteinPercentage")
                        .HasColumnType("float");

                    b.Property<float>("SkeletalMuscleMassPercentage")
                        .HasColumnType("float");

                    b.Property<float>("VisceralFat")
                        .HasColumnType("float");

                    b.Property<float>("WaterPercentage")
                        .HasColumnType("float");

                    b.Property<float>("WaterWeight")
                        .HasColumnType("float");

                    b.Property<float>("WeightSkeletalMuscleMassPercentage")
                        .HasColumnType("float");

                    b.Property<float>("Weigth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
